### ISSUE TITLE
Remove item from campaign within campaigns UI (incl. dependencies)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-campaign-admin#39]
## Problem
There is no way to remove pages/files from a campaign as yet, this is a pretty fundamental part of campaigns especially if you want to publish the campaign but don't want to publish a single item.

## AC's
* As a user, I am presented with an option to remove an item from a campaign
* If the item I want to remove doesn't have any dependencies then the item can be removed
* If the item has dependencies then I am informed that to remove this item I must also remove all dependencies
* If a selected item is removed (user should only be able to remove selected items as part of this issue) the item and preview disappear and the user is taken to the next item in the list if available
* Files that can be removed are removed instantly (there is no "Undo" functionality, nor any confirmation message)

## Excluded
* As a user I can opt to protect/safeguard an item from being published as part the campaign regardless of whether an item is explicitly added or implicitly added (see ...)
* As a user, I have the option to remove a parent without removing its children

## Designs
Aspiration of design direction (we will only build a sub-set of this functionality as part of this issue)
https://invis.io/DBCXO172C#/247538915_Campaigns_Camapgin_Detail_Preview_Item

Differences:
* Files that can be removed are removed instantly (there is no "Undo" functionality, nor any confirmation message)
* We are only implementing the "Remove from campaign" action within the more options drop-down on selected item preview panel
<img width="168" alt="pasted_image_23_08_17__1_58_pm" src="https://user-images.githubusercontent.com/555033/29595383-39ee13fc-880b-11e7-8ec6-a56e0b811f3a.png">
* If a selected item is removed (user should only be able to remove selected items as part of this issue) the item and preview disappear and the user is taken to the next item in the list if available. 

## Tasks

 - [x] Add remove button if item can be removed
 - [x] Add message if implicit item cannot be removed
 - [x] Confirmation before removing
 - [x] Confirm UX with @clarkepaul 
 
## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/207
- [ ] https://github.com/silverstripe/silverstripe-campaign-admin/pull/48

**Comment by clarkepaul** [comment]
I'm working on the UI design for this

**Comment by clarkepaul** [comment]
**Thinking out aloud here for notes**
* if a campaign contains a page (P1) and that page contains two images (F1 and F2)
* if a user chooses to remove P1 offer them two options:
   * remove all three items will be removed P1, F1, F2 (if not used elsewhere)
   * just remove P1 and leave F1, F2 in the campaign as explicitly added items
* if a user removes F1 options:
   * don't allow them to remove F1 unless all three are removed (good MVP)
   * leave in the campaign but put it in a untracked/blocked state (item will not be published), so that the preview still makes sense.
   * remove the one file and leave P1 and F2 (wont be clear with preview draft/publish states)

**Comment by clarkepaul** [comment]
Some mockups with the above notes put into a visual. I'll try to put past a few people for feedback—this mock would not all be implemented as part of this issue but needed to look at a slightly bigger picture. https://invis.io/DBCXO172C#/247538915_Campaigns_Camapgin_Detail_Preview_Item

**Comment by chillu** [comment]
@clarkepaul @newleeland Hmm, could we limit this to only allowing removal of explicitly added items? That would be a good starting point, since we don't need to deal with warning dialogs just yet.

Also, it's a bit counter-intuitive that you can't remove an item from a campaign in the same place that you added it (in "pages" and "assets" sections). Do we need a card to add an indicator on the edit screens if an item is already in a campaign? The "add to campaign" popup has made a start on this, but it's not really obvious enough.

![image](https://user-images.githubusercontent.com/111025/29504286-b434ff56-8692-11e7-83b3-7981006fe74b.png)

**Comment by flamerohr** [comment]
If we could limit the scope of removing to just explicit items, that would help simplify our approach to this story.
Implicit items are automatically added, and we do not have a mechanism to mark something as explicitly removed.
This also applies to explicit items added which were added implicitly as well, if you remove it, it'll come back because of the implicit relation is has.

Perhaps a more important point for this story is to make users aware that something cannot be removed because it is an implicit addition to the campaign.

@clarkepaul

**Comment by chillu** [comment]
Old ACs:

* As a user, I am presented with an option to remove an item from a campaign
* If the item I want to remove doesn't have any dependencies then the item can be removed
* If the item has dependencies then I am informed that to remove this item I must also remove all dependencies

New ACs:

* As a user, I am presented with an option to remove an item from a campaign
* The option is only available on explicitly added items
* The user knows why the option is not available on implicitly added items (can be a generic message like "please delete the owner")
* Implicitly added items related to the chosen item will be removed as well, unless there's other items referencing them in the same changeset

**Comment by chillu** [comment]
@newleeland @clarkepaul I've rewritten the ACs a bit: This is the baseline implementation, geared towards avoiding confirmation dialogs or other interactivity that would be time intensive to implement. Do you think that's workable? Can we split out a more complete solution into another card please?

**Comment by clarkepaul** [comment]
Designs added, I will go through this with whoever picks up the issue as it made more sense designing more of an aspiration for the direction of the design and we should only implement part of it.
